### PR TITLE
Add error handling for retryable KafkaErrors

### PR DESCRIPTION
**Pull request by nbaudis**

### CODE REVIEW

**Review by steven0711dong — APPROVED** [review]
LGTM

**Comment by steven0711dong** [comment]
I think this looks fine. Could you check whether this change would interfere with our existing logic of polling for only 2 seconds? If not, I think we can merge this. I checked and I don't think it's going to interfere with that logic. Could you also double check?

**Comment by nbaudis** [comment]
Good catch! Actually, this would have immediately retried polling if we got an error during the `__pollForMessages()` call. I've added a call to `updateLastPoll()` in the except block to prevent this.

**Review by groezing — APPROVED** [review]
Reviewed in a peer to peer session

**Pull request merged**
